name: Docker cache

inputs:
  context:
    default: .

  dockerfile:
    default: Dockerfile

  image:
    type: string

  tag:
    default: latest

  version:
    default: v2

runs:
  using: composite

  steps:
    - uses: docker/setup-buildx-action@v2

    - uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.image }}:${{ inputs.tag }}
        cache-from: type=gha,scope=docker-${{ inputs.version }}-${{ hashFiles('Dockerfile*') }} \
        cache-to: type=gha,mode=max,scope=docker-${{ inputs.version }}-${{ hashFiles('Dockerfile*') }}
        load: true # export the image from buildx cache & load into docker (sloooooooow)
