name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - "**"

  pull_request:
    branches:
      - "**:**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set environment up
        run: |
          docker-compose build
          docker-compose run --rm -e RAILS_ENV=test web bundle install
          docker-compose run --rm -e RAILS_ENV=test web bundle exec rake db:setup db:test:prepare elasticsearch:setup
          docker-compose up -d db elasticsearch redis sshd csv_watch ftp_monitor sidekiq

      - name: Run specs
        run: docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec

      - name: Run integration specs (rspec+capybara)
        run: docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec spec/features/**

      - name: Run integration specs (cucumber)
        run: docker-compose run --rm -e RAILS_ENV=test web bundle exec cucumber

  build:
    runs-on: ubuntu-latest
    needs: test
    if: contains('refs/heads/main', github.ref) || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/preview/') || startsWith(github.ref, 'refs/tags/')

    env:
      DOCKER_REPOSITORY: 'instedd/cdx'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
      - uses: actions/checkout@v2
      - name: Build image & push to Docker Hub
        run: ./build.sh
