name: Test

on:
  workflow_call:
    inputs:
      gemfile:
        required: true
        type: string

env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  COMPOSE_DEFAULT_SERVICE: web
  BUNDLE_GEMFILE: ${{ inputs.gemfile }}
  BUNDLE_LOCKFILE: ${{ inputs.gemfile }}.lock

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build web
      - uses: ./.github/actions/gems-cache

  unit:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build web
      - uses: ./.github/actions/gems-cache
      - uses: ./.github/actions/setup-databases

      - name: Run specs
        run: docker compose run --rm -e RAILS_ENV=test -e COVERAGE=true web bundle exec rspec

      - run: cp coverage/.resultset.json resultset.unit_tests.json

      - uses: actions/upload-artifact@v3
        with:
          name: unit_tests_coverage
          path: resultset.*.json
          retention-days: 1

  integration:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build web
      - uses: ./.github/actions/gems-cache
      - uses: ./.github/actions/setup-databases
      - run: docker compose up -d selenium

      - name: Run specs (capybara)
        run: docker compose run --rm -e RAILS_ENV=test -e COVERAGE=true -e FEATURES=true -e SELENIUM_URL web bundle exec rspec

      - name: Run specs (cucumber)
        run: docker compose run --rm -e RAILS_ENV=test -e COVERAGE=true -e SELENIUM_URL web bundle exec cucumber

      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Screenshots
          path: tmp/capybara/
          retention-days: 60

      - run: cp coverage/.resultset.json resultset.integration_tests.json

      - uses: actions/upload-artifact@v3
        with:
          name: integration_tests_coverage
          path: resultset.*.json
          retention-days: 1

  analysis:
    runs-on: ubuntu-latest
    needs:
      - unit
      - integration
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build web
      - uses: ./.github/actions/gems-cache

      - uses: actions/download-artifact@v3
        with:
          name: unit_tests_coverage
      - uses: actions/download-artifact@v3
        with:
          name: integration_tests_coverage

      - run: docker compose run --no-deps --rm web bundle exec rails coverage:report

      - uses: actions/upload-artifact@v3
        with:
          name: Coverage
          path: coverage/
          retention-days: 60

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            unit_tests_coverage
            integration_tests_coverage

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build web
      - uses: ./.github/actions/gems-cache

      - name: Lint Ruby files
        run: docker compose run --rm --no-deps web bundle exec rubocop --parallel
